---
- name: Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    file: external_repos
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no

- name: Install nginx
  become: yes
  become_method: sudo
  yum:
    name: nginx-1.10.2 
    state: present

- name: Create cfg file
  become: yes
  become_method: sudo
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Start nginx
  become: yes
  become_method: sudo
  service: name=nginx state=started
  #systemd:
  #  state: started
  #  name: nginx
