---

- name: Add Mongodb repo
  become: yes
  become_method: sudo
  yum_repository:
    name: mongodb-org-3.2
    description: mongdo db 3.2 repo
    file: /etc/yum.repos.d/mongodb-org-3.2.repo
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.2/x86_64/
    gpgcheck: yes
    enabled: yes

- name: Install mongodb package
  become: yes
  become_method: sudo
  yum: name={{ item }} state=installed
  with_items:
   - mongodb-org

- name: Start mongodb
  service: name=mongod state=started
  become: yes
  become_method: sudo
