---
sudo: required

services:
  - docker

language: python

python: 
  - "2.7"

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

before_install:
  - sudo apt-get update -qq
  - sudo pip install --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - pip --version
  - ansible --version
  - ansible-playbook -i development/hosts site.yml --syntax-check
  - java -version
  - docker --version
  - docker-compose --version
  - docker run --add-host=some_docker_container:127.0.0.1 --privileged -it -e "container=docker"  -v /sys/fs/cgroup:/sys/fs/cgroup -p 80:80 --name mycentos -d centos:7 /usr/sbin/init
  - ansible-playbook -i development/hosts site.yml -v 
  - sleep 15
  - curl localhost
  - curl localhost/info
