---
sudo: required

services:
  - docker

language: python

python: 
  - "2.7"

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

before_install:
  - sudo apt-get update -qq
  - sudo pip install --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - pip --version
  - ansible --version
  - ansible-playbook -i development/hosts site.yml --syntax-check
  - ansible-playbook -i staging/hosts site.yml --syntax-check
  - java -version
  - docker --version
  - docker-compose --version
  - docker run --add-host=some_docker_container:127.0.0.1 --privileged -d -e "container=docker" -e "MONGODB_PORT_27017_TCP_ADDR=127.0.0.1"  -v /sys/fs/cgroup:/sys/fs/cgroup -p 80:80 --name mycentos -d centos:7 /usr/sbin/init
  - ansible-playbook -i development/hosts site.yml
  - sleep 15
  - curl localhost
  - curl localhost/info | grep -q -i ansible
  - docker stop mycentos
  - docker-compose up -d
  - ansible-playbook -i staging/hosts site.yml
  - sleep 60
  - curl localhost
  - curl localhost/info | grep -q -i ansible
  - docker-compose stop
