---
- name: Create app folder
  become: yes
  become_method: sudo
  file:
    path: /opt/myapp/calcaulator-service
    state: directory
    #owner: hliu
    #group: hliu

- name: Download java 8 rpm
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm
    dest: /opt/myapp/calcaulator-service/jdk-8u121-linux-x64.rpm
    headers: 'Cookie: gpw_e24:http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    validate_certs: no
    checksum: sha1:bc94fc0d0c7dec448e55a222749258c0145ca914

- name: Install java 8 rpm from a local file
  yum:
    name: /opt/myapp/calcaulator-service/jdk-8u121-linux-x64.rpm
    state: present

- name: Download calculator-service.war
  get_url:
    url: https://jitpack.io/com/github/dev-tool-index/calculator-service/{{ calculator_service.version }}/calculator-service-{{ calculator_service.version }}.war
    dest: /opt/myapp/calcaulator-service/calculator-service.war
    checksum: sha1:51e0302cb6cf9a37b162dc9e0d224b5271a1965a

- name: Create file application.properties
  template:
    src: application.properties.j2
    dest: /opt/myapp/calcaulator-service/application.properties

- name: Kill calculator-service
  command: pkill -9 -f "server.port={{ calculator_service_http_port }} -jar"
  ignore_errors: True

- name: Start calculator-service
  shell: nohup java -Dspring.config.location=/opt/myapp/calcaulator-service/application.properties -Dserver.port={{ calculator_service_http_port }} -jar /opt/myapp/calcaulator-service/calculator-service.war >/dev/null 2>&1 &
  args:
    executable: /bin/bash
  environment:
    MONGODB_PORT_27017_TCP_ADDR: 127.0.0.1
  tags:
    - start-calculator-service
